### 5. **Arquivo de Configuração (`config.yaml`)**
data:
  simulated_data_path: "data/consumer_choices.csv"
  real_data_path: "data/real_transactions.csv"
  
model:
  latent_dim: 3
  learning_rate: 0.001
  epochs: 2000

inference:
  batch_size: 64
  test_size: 0.2